apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: docker-cred
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31110
   
---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJncHJlYyIsInBhc3N3b3JkIjoibmF2ZWVuQDk2IiwiYXV0aCI6IlozQnlaV002Ym1GMlpXVnVRRGsyIn19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-cred
type: kubernetes.io/dockerconfigjson
